AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LivestreamNotificatorFunction, Send notifications based on events from
  the Livestream server
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 20
Resources:
  LivestreamNotificatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: livestream.App::handleRequest
      Runtime: java8
      CodeUri: s3://sam-package-files/770dbdea11b266b34035ed97eb00dcac
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Events:
        LivestreamMessaging:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:eu-central-1:005887660038:livestream-messaging
Outputs:
  LivestreamNotificatorFunction:
    Description: Send notification based on events from the livestream server - Function
      ARN
    Value:
      Fn::GetAtt:
      - LivestreamNotificatorFunction
      - Arn
  LivestreamNotificatorFunctionIamRole:
    Description: Implicit IAM Role created for the livestream notificator function
    Value:
      Fn::GetAtt:
      - LivestreamNotificatorFunctionRole
      - Arn
