AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LivestreamNotificatorFunction, Send notifications based on events from
  the Livestream server
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 20
Resources:
  LivestreamNotificatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: livestream.App::handleRequest
      Runtime: java8
      CodeUri: s3://sam-package-files/549c4d3d62d174f5c640526c2c8936eb
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  MyServiceApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: MyServiceApi
  LivestreamNotificatorFunction:
    Description: Send notification based on events from the livestream server - Function
      ARN
    Value:
      Fn::GetAtt:
      - LivestreamNotificatorFunction
      - Arn
  LivestreamNotificatorFunctionIamRole:
    Description: Implicit IAM Role created for the livestream notificator function
    Value:
      Fn::GetAtt:
      - LivestreamNotificatorFunctionRole
      - Arn
