AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LivestreamNotificatorFunction

  Send notifications based on events from the Livestream server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20

Resources:

    LivestreamNotificatorFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: target/LivestreamNotificator-1.0.0-SNAPSHOT.jar
            Handler: livestream.App::handleRequest
            Runtime: java8
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
           #TODO: Remove api
                LivestreamNotificator:
                    Type: Api
                    Properties:
                        Path: /hello
                        Method: get
           #TODO: Add sns to process messages
           #TODO: Dead letter queue


Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    LivestreamNotificatorFunction:
      Description: "Send notification based on events from the livestream server - Function ARN"
      Value: !GetAtt LivestreamNotificatorFunction.Arn

    LivestreamNotificatorFunctionIamRole:
      Description: "Implicit IAM Role created for the livestream notificator function"
      Value: !GetAtt LivestreamNotificatorFunctionRole.Arn
