AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LivestreamNotificatorFunction, Send notifications based on events from the Livestream server
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 40

Resources:
  LivestreamNotificatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: livestream.Application::handleRequest
      Runtime: java8
      CodeUri: target/LivestreamNotificator-1.0.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Events:
        LivestreamMessaging:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:eu-central-1:005887660038:livestream-messaging

Outputs:
#  MyServiceApi:
#    Description: URL for application
#    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
#    Export:
#      Name: MyServiceApi

  LivestreamNotificatorFunction:
    Description: "Send notification based on events from the livestream server - Function ARN"
    Value: !GetAtt LivestreamNotificatorFunction.Arn

  LivestreamNotificatorFunctionIamRole:
    Description: "Implicit IAM Role created for the livestream notificator function"
    Value: !GetAtt LivestreamNotificatorFunctionRole.Arn
